// Generated by tools/sync-version.sh from the VERSION file at the repository root.
// Do not edit by hand: tools/check-version.sh fails when this disagrees with VERSION, and the
// release script refuses to run. Part 1 §1.3 of RELEASE.md — one authoritative value, every other
// appearance is a mirror.
//
// This is the only place in Sources/ that carries the version as a literal, which is what makes
// `grep -rE '"[0-9]+\.[0-9]+\.[0-9]+"' Sources/` a usable guard against a new hardcoded copy.

/// The version this build was built from.
///
/// Reported in the MCP `initialize` result and sent as the Parallel provider's `clientInfo.version`,
/// so a user can say which build they are running from the artifact alone (RELEASE.md §1.3).
public enum BuildVersion {
    public static let value = "1.3.0"
}
