#!/bin/bash
#
# Write every version mirror from the authoritative VERSION file.
#
# RELEASE.md §1.3: the version is single-sourced and enforced. `VERSION` at the repository root is
# authoritative; everything else is a mirror, and this is the one command that writes them. A bump is
# therefore one edit (VERSION) plus one command (this), and `tools/check-version.sh` fails in CI when
# a mirror disagrees.
#
# Usage:
#   tools/sync-version.sh            # write the mirrors
#   tools/sync-version.sh --stdout   # print what the mirror must contain, write nothing — this is
#                                    # what the check compares against, so the check never mutates
#                                    # the working tree (a check that rewrites the file it is
#                                    # checking can pass on an untracked file; that was a real bug)
#   tools/check-version.sh           # verify them (what CI runs)

set -euo pipefail

cd "$(dirname "$0")/.." || exit 1

mode="write"
case "${1:-}" in
    "") ;;
    --stdout) mode="stdout" ;;
    *)
        echo "usage: tools/sync-version.sh [--stdout]" >&2
        exit 2
        ;;
esac

version="$(tr -d '[:space:]' < VERSION)"

if ! printf '%s' "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
    echo "error: VERSION must be a bare semantic version X.Y.Z (no leading 'v', no suffix); found '$version'" >&2
    exit 1
fi

mirror="Sources/WebSearchCore/Support/BuildVersion.swift"

render() {
    cat <<EOF
// Generated by tools/sync-version.sh from the VERSION file at the repository root.
// Do not edit by hand: tools/check-version.sh fails when this disagrees with VERSION, and the
// release script refuses to run. Part 1 §1.3 of RELEASE.md — one authoritative value, every other
// appearance is a mirror.
//
// This is the only place in Sources/ that carries the version as a literal, which is what makes
// \`grep -rE '"[0-9]+\\.[0-9]+\\.[0-9]+"' Sources/\` a usable guard against a new hardcoded copy.

/// The version this build was built from.
///
/// Reported in the MCP \`initialize\` result and sent as the Parallel provider's \`clientInfo.version\`,
/// so a user can say which build they are running from the artifact alone (RELEASE.md §1.3).
public enum BuildVersion {
    public static let value = "$version"
}
EOF
}

if [ "$mode" = "stdout" ]; then
    render
    exit 0
fi

render > "$mirror"
echo "wrote $mirror -> $version"
echo
echo "Next: add a '## [$version]' section to CHANGELOG.md if it is a new version, then run"
echo "      tools/check-version.sh (CI does this too)."
